src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="project")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Stage::class, mappedBy="project")
     */
    private $stage;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profilePicture;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Cost::class, mappedBy="project")
     */
    private $costs;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $project_directory;

    /**
     * @ORM\OneToMany(targetEntity=Document::class, mappedBy="project_id", orphanRemoval=true)
     */
    private $documents;

    /**
     * @ORM\Column(type="float")
     */
    private $costEuro;


    /**
     * @ORM\Column(type="float")
     */
    private $costUsd;

    /**
     * @ORM\Column(type="float")
     */
    private $costRon;

    /**
     * @ORM\Column(type="float")
     */
    private $lng;

    /**
     * @ORM\Column(type="float")
     */
    private $lat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    public function __construct()
    {
        $this->stage = new ArrayCollection();
        $this->costs = new ArrayCollection();
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Stage[]
     */
    public function getStage(): Collection
    {
        return $this->stage;
    }

    public function addStage(Stage $stage): self
    {
        if (!$this->stage->contains($stage)) {
            $this->stage[] = $stage;
            $stage->setProject($this);
        }

        return $this;
    }

    public function removeStage(Stage $stage): self
    {
        if ($this->stage->removeElement($stage)) {
            // set the owning side to null (unless already changed)
            if ($stage->getProject() === $this) {
                $stage->setProject(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Cost[]
     */
    public function getCosts(): Collection
    {
        return $this->costs;
    }

    public function addCost(Cost $cost): self
    {
        if (!$this->costs->contains($cost)) {
            $this->costs[] = $cost;
            $cost->setProject($this);
        }

        return $this;
    }

    public function removeCost(Cost $cost): self
    {
        if ($this->costs->removeElement($cost)) {
            // set the owning side to null (unless already changed)
            if ($cost->getProject() === $this) {
                $cost->setProject(null);
            }
        }

        return $this;
    }

    public function getProjectDirectory(): ?string
    {
        return $this->project_directory;
    }

    public function setProjectDirectory(?string $project_directory): self
    {
        $this->project_directory = $project_directory;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setProjectId($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getProjectId() === $this) {
                $document->setProjectId(null);
            }
        }

        return $this;
    }

    public function getCostEuro(): ?float
    {
        return $this->costEuro;
    }

    public function setCostEuro(float $costEuro): self
    {
        $this->costEuro = $costEuro;

        return $this;
    }

    public function getCostUsd(): ?float
    {
        return $this->costUsd;
    }

    public function setCostUsd(float $costUsd): self
    {
        $this->costUsd = $costUsd;

        return $this;
    }

    public function getCostRon(): ?float
    {
        return $this->costRon;
    }

    public function setCostRon(float $costRon): self
    {
        $this->costRon = $costRon;

        return $this;
    }
    public function addCostsToProject(float $costEuro, float $costUsd, float $costRon){

        $currentCostEuro = $this->getCostEuro();
        $currentCostUsd = $this->getCostUsd();
        $currentCostRon = $this->getCostRon();

        $newCostEuro = $currentCostEuro + $costEuro;
        $newCostUsd = $currentCostUsd + $costUsd;
        $newCostRon = $currentCostRon + $costRon;

        self::setCostEuro($newCostEuro);
        self::setCostUsd($newCostUsd);
        self::setCostRon($newCostRon);
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ProfilePicture;

    /**
     * @ORM\OneToMany(targetEntity=Project::class, mappedBy="user")
     */
    private $project;

    /**
     * @ORM\OneToMany(targetEntity=Document::class, mappedBy="author", orphanRemoval=true)
     */
    private $documents;

    public function __construct()
    {
        $this->project = new ArrayCollection();
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->ProfilePicture;
    }

    public function setProfilePicture(?string $ProfilePicture): self
    {
        $this->ProfilePicture = $ProfilePicture;

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProject(): Collection
    {
        return $this->project;
    }

    public function addProject(Project $project): self
    {
        if (!$this->project->contains($project)) {
            $this->project[] = $project;
            $project->setUser($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->project->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getUser() === $this) {
                $project->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setAuthor($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getAuthor() === $this) {
                $document->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('ProfilePicture', FileType::class,[
                'label' => 'Profile picture(image only)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                'required' => true,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '10M',
                        'mimeTypesMessage' => 'Please upload a valid image',
                        'mimeTypes' => 'image/*'
                    ])
                ],
            ])
            ->add('lat',HiddenType::class)
            ->add('lng',HiddenType::class)
            ->add('address', HiddenType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('project_delete', {'slug': project.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.slug) }}">
    <a class="btn btn-danger"><i class="fas fa-times-circle"></i></button>
</form>

templates/project/_document.html.twig
<form method="post" action="">
    
    <input type="file"/>
</form>

templates/project/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}HouseBook | Edit Project{% endblock %}

{% block body %}
    <h1>Edit Project</h1>

    {{ include('project/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('project_index') }}">back to list</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HouseBook | Projects{% endblock %}

{% block body %}
    <div class="container-fluid"><h1>Projects</h1></div>
    <div class="container">
    <div class="row mb-5 cstm-height-card">
    {% for project in projects %}

		    <div class="project-card d-flex justify-content-between col-md-4 pb-5">
		    	<div class="card">
                <a href="{{ path('project_show', {'slug': project.slug}) }}">
                        <div class="d-flex justify-content-center">
                            <img src='{{asset ('/uploads/projects/'~ project.projectDirectory ~'/'~ project.profilePicture) }}' class="card-img" alt="...">
                        </div>
		    			<div class="card-body">
		    			    <h5 class="card-title">{{project.name}}</h5>
		    			    <p class="card-text mt-4">{{project.description}}</p>
                            <div class="card-text d-flex justify-content-between mt-4">
                                <p><i class='bx bxs-user'></i> {{project.user.firstName}} {{project.user.lastName}}</p>
                                <p><i class='bx bxs-calendar-alt'></i> {{project.createdAt|date("M d, y")}}</p>
                            </div>
                        </div>
		    	</a>
                </div>
		    </div>

    {% else %}
            <tr>
                <td colspan="3">No projects to show!Please create one!</td>
            </tr>
    {% endfor %}
    </div>
    <a class = "btn btn-primary" href="{{ path('project_new') }}">Create new</a>
{% endblock %}

templates/project/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}HouseBook | New Project{% endblock %}
{% block head %}


{% endblock %}
{% block body %}
    <h1>Create new Project</h1>

<body>
    {{ include('project/_form.html.twig') }}
    <div class="pac-card" id="pac-card">
        <div>
            <div id="title">Search address</div>
            <p>You can only input addresses!</p>
        </div>
        <div id="pac-container">
            <input id="pac-input" type="text" placeholder="Enter a location" />
        </div>
    </div>
    <div id="map"></div>
    <div id="infowindow-content">
        <span id="place-name" class="title"></span><br />
        <span id="place-address" ></span><br />
    </div>

    <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_iCIeZYa54exJQEYuAXAtPkQvWWwxzkQ&callback=initMap&libraries=places&v=weekly"
            defer
    ></script>


    <script>
        function initMap() {
            const map = new google.maps.Map(document.getElementById("map"), {
                center: { lat: 44.319305, lng: 23.800678 },
                zoom: 13,
                mapTypeControl: false,

            });
            const card = document.getElementById("pac-card");
            const input = document.getElementById("pac-input");
            const options = {
                fields: ["formatted_address", "geometry", "name"],
                strictBounds: false,
                types: ["address"],
            };

            map.controls[google.maps.ControlPosition.TOP_LEFT].push(card);

            const autocomplete = new google.maps.places.Autocomplete(input, options);



            const infowindow = new google.maps.InfoWindow();
            const infowindowContent = document.getElementById("infowindow-content");

            infowindow.setContent(infowindowContent);

            const marker = new google.maps.Marker({
                map,
                anchorPoint: new google.maps.Point(0, -29),
            });

            autocomplete.addListener("place_changed", () => {
                infowindow.close();
                marker.setVisible(false);

                const place = autocomplete.getPlace();

                if (!place.geometry || !place.geometry.location) {
                    // User entered the name of a Place that was not suggested and
                    // pressed the Enter key, or the Place Details request failed.
                    window.alert("No details available for input: '" + place.name + "'");
                    return;
                }

                // If the place has a geometry, then present it on a map.
                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                } else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(17);
                }

                marker.setPosition(place.geometry.location);
                marker.setVisible(true);
                infowindowContent.children["place-name"].textContent = place.name;
                infowindowContent.children["place-address"].textContent =
                    place.formatted_address;

                document.getElementById("project_lat").value = place.geometry.location.lat();
                document.getElementById("project_lng").value = place.geometry.location.lng();
                document.getElementById("project_address").value = place.formatted_address;
                infowindow.open(map, marker);

            });
        }

        window.initMap = initMap;
    </script>
    <a href="{{ path('project_index') }}">back to list</a>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}HouseBook | Project{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row first-row">

            <div class="col-12 col-sm-3 first-col">
                <img src={{asset ('/uploads/projects/'~ project.projectDirectory ~'/'~ project.profilePicture) }} class="project-image" alt="...">
            </div>

            <div class="col-12 col-sm-9 second-col">
                <div class="row project_title">
                    <div class="col-12 col-md-11 col-sm-11">
                        {{ project.name }} <br/>
                        {{ project.address }}
                    </div>
                    <div class="col-12 col-md-1 col-sm-1">
                        <form method="post" action="{{ path('project_delete', {'slug': project.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.slug) }}">
                            <button class="btn btn-delete"><i class='bx bxs-trash-alt bx-sm'></i></button>
                        </form>
                    </div>
                </div>
                <div class="row project_map">
                      <a class='nav_link project_link' data-toggle="modal" data-target=".bd-example-modal-lg"><i class='bx bxs-map'> </i> Open in maps</a>
                </div>
                <div class="row project_map project_info">
                    <div class="col">
                        <a class='nav_link project_link' href="{{path('cost_index', {'project':project.slug})}}">
                            <i class='bx bxs-dollar-circle'></i>{{ project.costusd }} Invested
                        </a>
                    </div>
                    <div class="col">
                        <a class='nav_link project_link' href="{{path('document_index', {'project':project.slug})}}">
                            <i class='bx bxs-file'></i>{{project.documents|length}} Documents
                        </a>
                    </div>
                    {% set count = 0 %}
                    {% for stage in project.stage %}
                        {% for step in stage.steps %}
                            {% set count = count + 1 %}
                        {% endfor %}
                    {% endfor %}
                    <div class="col">
                        <a class='nav_link project_link' href="{{ path('steps_index', {'project':project.slug}) }}">
                            <i class='bx bxs-layer' ></i>   {{ count }} Steps in project
                        </a>
                    </div>
                </div>
                <div class="row d-flex align-content-center project_map project_button_row">
                    <div class="col-12 col-md-6 col-sm-12 d-flex justify-content-center">
                        <a class="btn nav_link project_link project_btn rounded-pill" href="{{ path('document_new', {'slug': project.slug}) }}">
                            <i class='bx bx-folder-plus bx-sm'></i>New document
                        </a>
                        <a href="{{ path('cost_new', {'slug': project.slug}) }}" class="btn nav_link project_link project_btn rounded-pill">
                            <i class='bx bx-wallet bx-sm' ></i>New cost
                        </a>
                    </div>
                    <div class="col-12 col-md-6 col-sm-12 d-flex justify-content-center">

                    </div>

                </div>

            </div>
        </div>
        <div class="row second-row">
            <h3 class="project-description">{{ project.description }}</h3>
            <p class ="d-none" id="project_lat">{{project.lat}} </p>
            <p class ="d-none" id="project_lng">{{project.lng}} </p>
            <div class="row row-section"></div>
                <div class="col-12 col-md-12 col-lg-4">
                    <div class="row d-flex project-stage">
                        <div class="col-8 project-description">Stages for this project</div>
                        <div class="col-4">
                            <a href="{{ path('stage_new', {'slug': project.slug}) }}" class="add-link" ><i class='bx bxs-layer-plus bx-sm'></i></a>
                        </div>
                    </div>
                        <ol>
                        {% for stage in project.stage %}

                            <li>
                                {{ stage.name}}
                                <a href="{{ path('steps_new', {'slug': stage.slug}) }}" class="add-link"><i class="fas fa-plus-circle"></i></a>
                                {{ include('stage/_delete_form.html.twig') }}
                            </li>
                            <ol>
                            {% for step in stage.steps %}

                                <li><a href="{{path('steps_show',{'slug': step.slug})}}">{{step.name}}</a>
                                {% if (step.document|length > 0) or (step.cost|length > 0) %}
                                ({{step.document|length}} documents, {{step.cost|length}} costs)
                                {% endif %}


                                </li>
                            {% endfor %}
                            </ol>
                        {% endfor %}
                    </ol>

                </div>
                <div class="col-12 col-md-12 col-lg-4">
                    Section 2
                </div>
                <div class="col-12 col-md-12 col-lg-4">
                    {% if project.documents|length >3 %}
                        <p class="folder-icon">Last 3 documents of this project...</p>
                    {% endif%}
                    {% for document in project.documents|slice(-3) %}
                        <div class="row document-show align-items-center">
                            <div class="col-2 d-flex">
                                <i class='bx bxs-file bx-lg folder-icon'></i>
                            </div>
                            <div class="col-8 document-info">
                                <div class="document-name">{{document.name}}</div>
                                <div class="document-ext">{{document.name|split('.',2)[1]}}</div>
                            </div>
                            <div class="col-2">
                                <a class="document-download" href="{{ path('document_download', {'file': document.path}) }}"><i class='bx bx-down-arrow-circle  bx-md'></i></a>
                            </div>
                        </div>
                    {% endfor %}
                    {% if project.documents|length >3 %}
                            <a href = "{{path('document_index', {'project':project.slug})}}" class="show-more">Show more...</a>
                    {% endif%}
                </div>
        </div>


    </div>
    <div id="infowindow-content">
        <span id="place-name" class="title">{{project.name}}</span><br />
        <span id="place-address" >{{project.Description}}</span><br />
    </div>



    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Project's location on the map</h5>
                    <a type="button" class="close nav_link project_link" data-dismiss="modal" aria-label="Close">
                        <i class='bx bx-x bx-md'></i>
                    </a>
                </div>
                <div class="modal-body">
                    <div id="map"></div>
                    <div id="infowindow-content">
                        <span id="place-name" class="title"></span><br />
                        <span id="place-address" ></span><br />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_iCIeZYa54exJQEYuAXAtPkQvWWwxzkQ&callback=initMap&libraries=places&v=weekly"
            defer
    ></script>
    <script>
        let map;
        let service;
        let infowindow;

        function initMap() {
            const project_lat = document.getElementById("project_lat").textContent;
            const project_lng = document.getElementById("project_lng").textContent;

            const project = new google.maps.LatLng(project_lat, project_lng);

            map = new google.maps.Map(document.getElementById("map"), {
                center: project,
                zoom: 15,
            });

            marker = new google.maps.Marker({
                position: project,
                map
            });
            const infowindow = new google.maps.InfoWindow();
            const infowindowContent = document.getElementById("infowindow-content");

            infowindow.setContent(infowindowContent);

            infowindow.open(map, marker);

        }

        window.initMap = initMap;
    </script>
{% endblock %}